FROM python:3.11.7-slim

WORKDIR /workspace

RUN pip install --no-cache-dir \
    tensorflow==2.16.1 \
    tensorflow-intel==2.12.0 \
    tf-keras==2.15.0 \
    keras==3.3.3 \
    tensorboard==2.16.2 \
    torch==2.3.0 \
    torchvision==0.18.0 \
    efficientnet==1.0.0 \
    segmentation-models==1.0.1 \
    image-classifiers==1.0.0 \
    jupyterlab

EXPOSE 8888

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
