FROM python:3.11.7-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    scikit-learn \
    joblib

COPY main.py .
COPY model.pkl .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
